import uuid
import enum
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    ForeignKey,
    Float,
    Text,
    Enum as SAEnum,
    Index,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.base import Base

if TYPE_CHECKING:
    from app.features.cases.models import Case
    from app.features.documents.models import Document
    from app.features.users.models import User


# ─────────────────────────────
# Enums
# ─────────────────────────────
class ExtractionStatus(str, enum.Enum):
    pending = "pending"
    processing = "processing"
    completed = "completed"
    failed = "failed"


class ReviewStatus(str, enum.Enum):
    pending = "pending"
    accepted = "accepted"
    rejected = "rejected"
    edited = "edited"


# ─────────────────────────────
# Extraction Result
# ─────────────────────────────
class ExtractionResult(Base):
    __tablename__ = "extraction_results"

    __table_args__ = (
        UniqueConstraint("document_id", name="uq_extraction_document"),
        Index("ix_extraction_case", "case_id"),
        Index("ix_extraction_status", "extraction_status"),
        Index("ix_extraction_review", "review_status"),
        Index("ix_extraction_case_status", "case_id", "extraction_status"),
    )

    # Identity
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Extraction Data
    extracted_fields: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
    )

    raw_ai_response: Mapped[Optional[str]] = mapped_column(Text)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float)

    # Review content for the form-based extraction reviewer.
    # Generated by backend after extraction; user edits stored here too.
    formatted_content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Status
    extraction_status: Mapped[ExtractionStatus] = mapped_column(
        SAEnum(ExtractionStatus, name="extraction_status"),
        nullable=False,
        default=ExtractionStatus.pending,
        index=True,
    )

    review_status: Mapped[ReviewStatus] = mapped_column(
        SAEnum(ReviewStatus, name="review_status"),
        nullable=False,
        default=ReviewStatus.pending,
        index=True,
    )

    # Review Metadata
    reviewed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
    )

    reviewed_at: Mapped[Optional[datetime]]
    user_edits: Mapped[Optional[dict]] = mapped_column(JSONB)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        default=func.now(),
        onupdate=func.now(),
    )

    # Relations
    document: Mapped["Document"] = relationship(
        "Document",
        back_populates="extraction_result",
        lazy="selectin",
    )

    case: Mapped["Case"] = relationship(
        "Case",
        back_populates="extraction_results",
        lazy="selectin",
    )

    reviewer: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[reviewed_by],
        lazy="selectin",
    )


# ─────────────────────────────
# Typed Version (AI typing)
# ─────────────────────────────
class TypedVersion(Base):
    __tablename__ = "typed_versions"

    __table_args__ = (
        UniqueConstraint("document_id", name="uq_typed_document"),
        Index("ix_typed_status", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    typed_content: Mapped[str] = mapped_column(Text, nullable=False)
    raw_ai_response: Mapped[Optional[str]] = mapped_column(Text)
    # Dedicated audit trail from the Typing Agent (processing_notes pipe string).
    # raw_ai_response kept for backward-compat; agent_notes is the canonical field.
    agent_notes: Mapped[Optional[str]] = mapped_column(Text)

    status: Mapped[ReviewStatus] = mapped_column(
        SAEnum(ReviewStatus, name="review_status", create_type=False),
        nullable=False,
        default=ReviewStatus.pending,
        index=True,
    )

    reviewed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
    )

    reviewed_at: Mapped[Optional[datetime]]

    created_at: Mapped[datetime] = mapped_column(default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        default=func.now(),
        onupdate=func.now(),
    )

    document: Mapped["Document"] = relationship(
        "Document",
        back_populates="typed_version",
        lazy="selectin",
    )

    reviewer: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[reviewed_by],
        lazy="selectin",
    )
