"""add cause_listings

Revision ID: 41f9d334676c
Revises: 0004
Create Date: 2026-05-03 11:13:25.941393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41f9d334676c"
down_revision: Union[str, Sequence[str], None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cause_listings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("listing_date", sa.Date(), nullable=False),
        sa.Column("court_number", sa.String(length=20), nullable=False),
        sa.Column("serial_number", sa.Integer(), nullable=True),
        sa.Column("case_number", sa.String(length=200), nullable=True),
        sa.Column("case_title", sa.String(length=1000), nullable=True),
        sa.Column("petitioner", sa.String(length=500), nullable=True),
        sa.Column("respondent", sa.String(length=500), nullable=True),
        sa.Column("advocate_name", sa.String(length=500), nullable=True),
        sa.Column("case_type_raw", sa.String(length=200), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column("raw_row_text", sa.Text(), nullable=True),
        sa.Column("matched_case_id", sa.UUID(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["matched_case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_date",
            "court_number",
            "serial_number",
            name="idx_cause_listings_unique",
        ),
    )
    op.create_index(
        op.f("ix_cause_listings_case_number"),
        "cause_listings",
        ["case_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cause_listings_listing_date"),
        "cause_listings",
        ["listing_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cause_listings_matched_case_id"),
        "cause_listings",
        ["matched_case_id"],
        unique=False,
    )
    op.alter_column(
        "case_access",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_case_access_case_id"), table_name="case_access")
    op.drop_index(op.f("idx_case_access_user_id"), table_name="case_access")
    op.create_index(
        op.f("ix_case_access_case_id"), "case_access", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_access_user_id"), "case_access", ["user_id"], unique=False
    )
    op.alter_column(
        "case_contexts",
        "last_updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "case_contexts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("case_contexts_case_id_key"), "case_contexts", type_="unique"
    )
    op.drop_index(op.f("idx_case_contexts_case_id"), table_name="case_contexts")
    op.create_index(
        op.f("ix_case_contexts_case_id"), "case_contexts", ["case_id"], unique=True
    )
    op.alter_column(
        "case_numbers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_case_numbers_case_id"), table_name="case_numbers")
    op.drop_index(op.f("idx_case_numbers_number"), table_name="case_numbers")
    op.create_index(
        op.f("ix_case_numbers_case_id"), "case_numbers", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_numbers_case_number"),
        "case_numbers",
        ["case_number"],
        unique=False,
    )
    op.alter_column(
        "case_sections",
        "added_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "case_sections",
        "removed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_case_sections_active"),
        table_name="case_sections",
        postgresql_where="(is_active = true)",
    )
    op.drop_index(op.f("idx_case_sections_case_id"), table_name="case_sections")
    op.create_index(
        op.f("ix_case_sections_case_id"), "case_sections", ["case_id"], unique=False
    )
    op.alter_column(
        "case_summaries",
        "generated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "case_summaries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("case_summaries_case_id_key"), "case_summaries", type_="unique"
    )
    op.drop_index(op.f("idx_case_summaries_case_id"), table_name="case_summaries")
    op.create_index(
        op.f("ix_case_summaries_case_id"), "case_summaries", ["case_id"], unique=True
    )
    op.alter_column(
        "cases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "cases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_cases_lawyer_id"), table_name="cases")
    op.drop_index(
        op.f("idx_cases_next_hearing"),
        table_name="cases",
        postgresql_where="(status = 'active'::case_status)",
    )
    op.drop_index(op.f("idx_cases_status"), table_name="cases")
    op.create_index(op.f("ix_cases_lawyer_id"), "cases", ["lawyer_id"], unique=False)
    op.create_index(
        op.f("ix_cases_next_hearing_date"), "cases", ["next_hearing_date"], unique=False
    )
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.alter_column(
        "documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "documents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_documents_case_id"), table_name="documents")
    op.drop_index(
        op.f("idx_documents_ocr_status"),
        table_name="documents",
        postgresql_where="(ocr_status = ANY (ARRAY['pending'::ocr_status, 'processing'::ocr_status]))",
    )
    op.drop_index(op.f("idx_documents_uploaded_by"), table_name="documents")
    op.create_index(
        op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_uploaded_by"), "documents", ["uploaded_by"], unique=False
    )
    op.alter_column(
        "draft_exports",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "draft_exports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_draft_exports_draft_id"), table_name="draft_exports")
    op.create_index(
        op.f("ix_draft_exports_draft_id"), "draft_exports", ["draft_id"], unique=False
    )
    op.alter_column(
        "drafts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "drafts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_drafts_case_id"), table_name="drafts")
    op.drop_index(op.f("idx_drafts_created_by"), table_name="drafts")
    op.drop_index(op.f("idx_drafts_status"), table_name="drafts")
    op.create_index(op.f("ix_drafts_case_id"), "drafts", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_drafts_created_by"), "drafts", ["created_by"], unique=False
    )
    op.alter_column(
        "extraction_results",
        "reviewed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "extraction_results",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "extraction_results",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_extraction_fields_gin"),
        table_name="extraction_results",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("idx_extraction_results_case_id"), table_name="extraction_results"
    )
    op.drop_index(
        op.f("idx_extraction_results_document_id"), table_name="extraction_results"
    )
    op.drop_index(
        op.f("idx_extraction_results_review"), table_name="extraction_results"
    )
    op.create_index(
        op.f("ix_extraction_results_case_id"),
        "extraction_results",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_results_document_id"),
        "extraction_results",
        ["document_id"],
        unique=False,
    )
    op.alter_column(
        "parties",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "parties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_parties_case_id"), table_name="parties")
    op.create_index(op.f("ix_parties_case_id"), "parties", ["case_id"], unique=False)
    op.alter_column(
        "typed_versions",
        "reviewed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "typed_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "typed_versions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_typed_versions_document_id"), table_name="typed_versions")
    op.drop_constraint(
        op.f("typed_versions_document_id_key"), "typed_versions", type_="unique"
    )
    op.create_index(
        op.f("ix_typed_versions_document_id"),
        "typed_versions",
        ["document_id"],
        unique=True,
    )
    op.alter_column(
        "users",
        "last_login_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_index(op.f("idx_users_role"), table_name="users")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "last_login_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_typed_versions_document_id"), table_name="typed_versions")
    op.create_unique_constraint(
        op.f("typed_versions_document_id_key"),
        "typed_versions",
        ["document_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_typed_versions_document_id"),
        "typed_versions",
        ["document_id"],
        unique=False,
    )
    op.alter_column(
        "typed_versions",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "typed_versions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "typed_versions",
        "reviewed_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_parties_case_id"), table_name="parties")
    op.create_index(op.f("idx_parties_case_id"), "parties", ["case_id"], unique=False)
    op.alter_column(
        "parties",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "parties",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_extraction_results_document_id"), table_name="extraction_results"
    )
    op.drop_index(
        op.f("ix_extraction_results_case_id"), table_name="extraction_results"
    )
    op.create_index(
        op.f("idx_extraction_results_review"),
        "extraction_results",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_extraction_results_document_id"),
        "extraction_results",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_extraction_results_case_id"),
        "extraction_results",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_extraction_fields_gin"),
        "extraction_results",
        ["extracted_fields"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "extraction_results",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "extraction_results",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "extraction_results",
        "reviewed_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_drafts_created_by"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_case_id"), table_name="drafts")
    op.create_index(op.f("idx_drafts_status"), "drafts", ["status"], unique=False)
    op.create_index(
        op.f("idx_drafts_created_by"), "drafts", ["created_by"], unique=False
    )
    op.create_index(op.f("idx_drafts_case_id"), "drafts", ["case_id"], unique=False)
    op.alter_column(
        "drafts",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "drafts",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_draft_exports_draft_id"), table_name="draft_exports")
    op.create_index(
        op.f("idx_draft_exports_draft_id"), "draft_exports", ["draft_id"], unique=False
    )
    op.alter_column(
        "draft_exports",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "draft_exports",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_documents_uploaded_by"), table_name="documents")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.create_index(
        op.f("idx_documents_uploaded_by"), "documents", ["uploaded_by"], unique=False
    )
    op.create_index(
        op.f("idx_documents_ocr_status"),
        "documents",
        ["ocr_status"],
        unique=False,
        postgresql_where="(ocr_status = ANY (ARRAY['pending'::ocr_status, 'processing'::ocr_status]))",
    )
    op.create_index(
        op.f("idx_documents_case_id"), "documents", ["case_id"], unique=False
    )
    op.alter_column(
        "documents",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index(op.f("ix_cases_next_hearing_date"), table_name="cases")
    op.drop_index(op.f("ix_cases_lawyer_id"), table_name="cases")
    op.create_index(op.f("idx_cases_status"), "cases", ["status"], unique=False)
    op.create_index(
        op.f("idx_cases_next_hearing"),
        "cases",
        ["next_hearing_date"],
        unique=False,
        postgresql_where="(status = 'active'::case_status)",
    )
    op.create_index(op.f("idx_cases_lawyer_id"), "cases", ["lawyer_id"], unique=False)
    op.alter_column(
        "cases",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "cases",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_case_summaries_case_id"), table_name="case_summaries")
    op.create_index(
        op.f("idx_case_summaries_case_id"), "case_summaries", ["case_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("case_summaries_case_id_key"),
        "case_summaries",
        ["case_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "case_summaries",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "case_summaries",
        "generated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_case_sections_case_id"), table_name="case_sections")
    op.create_index(
        op.f("idx_case_sections_case_id"), "case_sections", ["case_id"], unique=False
    )
    op.create_index(
        op.f("idx_case_sections_active"),
        "case_sections",
        ["case_id"],
        unique=False,
        postgresql_where="(is_active = true)",
    )
    op.alter_column(
        "case_sections",
        "removed_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "case_sections",
        "added_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_case_numbers_case_number"), table_name="case_numbers")
    op.drop_index(op.f("ix_case_numbers_case_id"), table_name="case_numbers")
    op.create_index(
        op.f("idx_case_numbers_number"), "case_numbers", ["case_number"], unique=False
    )
    op.create_index(
        op.f("idx_case_numbers_case_id"), "case_numbers", ["case_id"], unique=False
    )
    op.alter_column(
        "case_numbers",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_case_contexts_case_id"), table_name="case_contexts")
    op.create_index(
        op.f("idx_case_contexts_case_id"), "case_contexts", ["case_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("case_contexts_case_id_key"),
        "case_contexts",
        ["case_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "case_contexts",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "case_contexts",
        "last_updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_case_access_user_id"), table_name="case_access")
    op.drop_index(op.f("ix_case_access_case_id"), table_name="case_access")
    op.create_index(
        op.f("idx_case_access_user_id"), "case_access", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_case_access_case_id"), "case_access", ["case_id"], unique=False
    )
    op.alter_column(
        "case_access",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_cause_listings_matched_case_id"), table_name="cause_listings"
    )
    op.drop_index(op.f("ix_cause_listings_listing_date"), table_name="cause_listings")
    op.drop_index(op.f("ix_cause_listings_case_number"), table_name="cause_listings")
    op.drop_table("cause_listings")
    # ### end Alembic commands ###
