"""add courtroom_sessions

Revision ID: cd92237d23b8
Revises: 41f9d334676c
Create Date: 2026-05-03 11:18:43.414592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cd92237d23b8"
down_revision: Union[str, Sequence[str], None] = "41f9d334676c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courtroom_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("lawyer_id", sa.UUID(), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum("opposing_counsel", "judge", name="sessiontype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "weak_points_identified",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "archived", name="sessionstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["lawyer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_courtroom_sessions_case_id"),
        "courtroom_sessions",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_courtroom_sessions_lawyer_id"),
        "courtroom_sessions",
        ["lawyer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_courtroom_sessions_status"),
        "courtroom_sessions",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courtroom_sessions_status"), table_name="courtroom_sessions")
    op.drop_index(
        op.f("ix_courtroom_sessions_lawyer_id"), table_name="courtroom_sessions"
    )
    op.drop_index(
        op.f("ix_courtroom_sessions_case_id"), table_name="courtroom_sessions"
    )
    op.drop_table("courtroom_sessions")
    # ### end Alembic commands ###
